# This is the name of our workflow. It will show up in the "Actions" tab on GitHub.
name: Deploy Website to cPanel

# This section defines when the workflow should run.
on:
  # This makes it run automatically every time you push to the main branch.
  push:
    branches: [ "main" ]
  
  # This adds the manual "Run workflow" button in the GitHub Actions UI.
  workflow_dispatch:

# This section defines the actual work to be done.
jobs:
  # We'll have a single job called "deploy"
  deploy:
    # The job will run on a fresh, virtual computer provided by GitHub (Ubuntu is a good choice)
    runs-on: ubuntu-latest
    
    # These are the individual steps the job will take
    steps:
      # Step 1: Check out a copy of your repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Build the project
      - name: Build project
        run: npm run build

      # Step 5: Deploy built files via SFTP (no rsync, password supported)
      - name: FTP Upload
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.SSH_HOST }}           #
          username: ${{ secrets.SSH_USERNAME }}     
          password: ${{ secrets.SSH_PASSWORD }}     # 
          port: ${{ secrets.SSH_PORT }}             # to: 21 for FTP, but keeping variable
          local-dir: './dist/'
          server-dir: ${{ secrets.SSH_TARGET_DIR }} # set to: /public_html/ (or your actual web root)
          protocol: ftp
          dangerous-clean-slate: false